name: Upload to PyPI

on:
  push:
    tags: ["v*"]
  workflow_dispatch: # ← 新增这一行
    inputs:
      tag:
        description: 'Git tag to release (e.g. v1.2.3)'
        required: true
        type: string

jobs:
  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Build sources
        run: |-
          pip install build
          python -mbuild -n -s
      - name: Upload sources
        uses: actions/upload-artifact@v6
        with:
          name: dist-sources
          path: dist/*.tar.gz
          retention-days: 2

  build-wheels:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - { os: windows-2025,     cibw_arch: AMD64 }
          - { os: windows-11-arm,   cibw_arch: ARM64 }
          - { os: ubuntu-24.04,     cibw_arch: x86_64 }
          - { os: ubuntu-24.04-arm, cibw_arch: aarch64 }
          - { os: macos-15,         cibw_arch: arm64 }
          - { os: macos-15-intel,   cibw_arch: x86_64 }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3
        env:
          CIBW_ARCHS: ${{matrix.cibw_arch}}
          CIBW_SKIP: "*-musllinux_aarch64"
          CIBW_TEST_SKIP: "*-win_* cp31?t-*"
      - name: Upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: dist-wheels-${{matrix.os}}-${{matrix.cibw_arch}}
          path: wheelhouse/*.whl
          retention-days: 2

  release:
    runs-on: ubuntu-latest
    needs: [build-sdist, build-wheels]
    permissions:
      id-token: write   # 让 PyPI 可信发布拿到 OIDC 令牌
      contents: read    # 可选，但 gh release create 需要
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          path: dist
          pattern: dist-*
          merge-multiple: true
      - name: Check artifacts
        run: ls -l dist
      - name: Create GitHub release
        run: gh release create "$GITHUB_REF_NAME" --generate-notes
        env:
          GH_TOKEN: ${{github.token}}
          GH_REPO: ${{github.repository}}
